name: Build and deploy development

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          architecture: x64

      - name: Run all tests
        env:
          JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
        run: mvn test -Dspring.profiles.active=test
