name: Build and deploy development

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          architecture: x64

      - name: Grant permissions to ./gradle
        run: chmod +x gradlew

      - name: Run all tests
        run: ./gradlew test --tests "*" -Dspring.profiles.active=test
